# Generated by Django 4.2.7 on 2023-11-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='contact',
            new_name='kontak',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='pesan',
        ),
    ]
