# Generated by Django 4.2.7 on 2023-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_analytic_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='device_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='request_method',
            field=models.CharField(blank=True, null=True),
        ),
    ]
