# Generated by Django 4.2.7 on 2023-11-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0003_alter_analytic_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='view_count',
        ),
    ]
