# Generated by Django 4.2.7 on 2023-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0004_remove_analytic_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='post_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
